repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: check-case-conflict
  - id: check-json
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: no-commit-to-branch
    args:
    - "-b main"
    - "-b develop"
- repo: local
  hooks:
  - id: isort
    name: isort
    entry: poetry run isort
    language: system
    types: [python]
    require_serial: true
  - id: black
    name: black
    entry: poetry run black
    language: system
    types: [python]
    require_serial: true
  - id: flake8
    name: flake8
    entry: poetry run flake8
    language: system
    types: [python]
    require_serial: true
  - id: mypy
    name: mypy
    entry: poetry run mypy
    language: system
    types: [python]
    require_serial: true
